#include "dialog_speech.h"

#include <windows.h>
#include <cstdint>
#include <cstring>

#include "engine_area.h"      // GameObjectKind, GetObjectKind
#include "hotkeys.h"          // Action::DialogRepeatLine (R re-speaks the line)
#include "engine_manager.h"   // kAddrGuiManagerPtr, kMgrPanels*
#include "engine_offsets.h"
#include "engine_panels.h"    // PanelKind, IdentifyPanel
#include "engine_player.h"    // GetPlayerServerCreature
#include "engine_reads.h"
#include "log.h"
#include "menus_extract.h"    // FromControl
#include "menus_modsettings.h" // GetToggle(Option::HumanSubtitles)
#include "prism.h"
#include "transitions.h"      // IsModuleLoadPending — gate during cutscene-load
#include "tutorial_hints.h"   // HintForDialogLine — detect a rewritten tutorial line
#include "tutorial_popup.h"   // RecordPendingHint — fire a popup at the reply break
                              // transient (engine LYT loader use-after-free)

namespace acc::dialog_speech {

namespace {

// ---- Human-speaker classifier --------------------------------------------
//
// Vanilla appearance.2da has 509 rows. We classify each row as "human" or
// "non-human" by label-prefix matching at build time (see
// build/dump-2da/Program.cs), then pack the result into a 512-bit bitmask
// keyed by appearance_type. At runtime we read CSWSCreature.appearance
// (+0xa4c) off the conversation partner and look up the bit.
//
// FALSE-NEGATIVE BIAS: when uncertain, the build-time classifier marks a
// row non-human, so the line stays spoken. Suppressing an alien by mistake
// would lock the player out of the only comprehensible channel (subtitle);
// failing to suppress a human is merely an annoying VO/TTS overlap.
//
// The engine RACE enum (HUMAN=6, DROID=5, only two values) is too coarse —
// Twi'leks, Cathar, Echani, Mandalorians all bucket as HUMAN at the rules
// level. appearance_type is the only field that distinguishes "Human
// Player Male" from "Twi'lek Female". Per-creature exceptions (Vrook uses
// N_CommM but is Cathar, etc.) are baked into the build-time classifier.
//
// "Human" here is shorthand for the real criterion: the speaker delivers an
// intelligible Basic line with full VO, so reading the subtitle would just
// talk over a voice the player already understands. That is almost always a
// human appearance, but a few non-human party members qualify too — Mission
// (Twi'lek) and Juhani (Cathar) both speak Basic and are voiced, so their
// unique appearance rows are classified "human" to suppress the overlap.
// Genuinely alien speakers (Zaalbar/Shyriiwook, the generic Twi'lek crowd)
// stay non-human so their subtitles remain the player's only channel.
//
// Mod compatibility: any mod that adds new appearance.2da rows will fall
// past kHumanAppearanceMaxId and classify as non-human (TTS stays on).
// That's the safe direction.

// Generated by build/dump-2da/Program.cs — DO NOT hand-edit. To refresh:
//   cd build/dump-2da && dotnet run > human-mask.txt 2> human-rows.txt
// then paste the constexpr block here. 341 human rows of 509.
constexpr int    kHumanAppearanceMaxId     = 508;
constexpr size_t kHumanAppearanceWordCount = 8;
constexpr uint64_t kHumanAppearanceMask[kHumanAppearanceWordCount] = {
    0x00001e67deffedf0ULL,
    0xfffffffff8000000ULL,
    0xff3fffffffffffffULL,
    0x0000000fffffffffULL,
    0x181ffffff8800020ULL,
    0x2d9f9ff87ffc3806ULL,
    0x344ff7e3fffffff6ULL,
    0x1ffffff7ffffffc0ULL,
};

bool IsHumanAppearance(int appearanceType) {
    if (appearanceType < 0 || appearanceType > kHumanAppearanceMaxId) return false;
    unsigned idx  = static_cast<unsigned>(appearanceType);
    return (kHumanAppearanceMask[idx >> 6] >> (idx & 63)) & 1ULL;
}

// RACE enum value for droids (see engine_offsets.h kCreatureStatsRaceOffset).
constexpr int kRaceDroid = 5;

// ---- Speaker resolution chain --------------------------------------------
//
// PRIMARY (per-line, covers overheard NPC-to-NPC):
//   gui = ResolveGuiInGame()  (CGuiInGame*)
//     ↓ +0x170  current_dialog_speaker (CLIENT object id)
//   ClientToServerObjectId → ResolveServerObjectHandle → CSWSObject*
//
// FALLBACK (1-on-1 dialog + barks where the GUI field isn't populated):
//   player = GetPlayerServerCreature()  (CSWSCreature*)
//     ↓ +0x54  dialog_owner (SERVER object id)
//   ResolveServerObjectHandle → CSWSObject*
//
// Either way we land on a CSWSObject*, validate kind == Creature(5), then
// read +0xa74 stats → +0x186 appearance / +0xdc race. The GUI field is
// authoritative for the *current line's* speaker; the player-partner field
// only ever names the player's own conversation partner, so it's wrong in
// multi-party / overheard scenes — hence GUI-first.
//
// Returns false if no link resolves, the object isn't a creature, or SEH
// faults — caller treats false as "unknown speaker, default to speaking".
struct SpeakerInfo {
    void* speaker;          // CSWSCreature* (validated via kind=Creature)
    int   appearance;       // appearance.2da row index, -1 if unread
    int   raceEnum;         // RACE enum (HUMAN=6, DROID=5, 0 otherwise)
    char  tag[32];          // CSWSObject.tag (or "" if unread)
};

// Per-tag never-suppress allowlist. These speakers classify as
// human/droid by appearance or race, but their subtitle is nonetheless the
// player's only channel, so it must always be spoken regardless of the
// HumanSubtitles toggle. Matched case-insensitively on CSWSObject.tag.
//
//   - "sasha": Child_Female appearance (classified human), but she speaks an
//     untranslated invented language with NO per-line VO at all. Her subtitle
//     — including the bracketed stage directions that decode the words by
//     gesture — is the entire content of her language-learning sidequest.
//     Suppressing it silences 100% of her side of the conversation.
//   - "vek": wears Sith_Male_Twilek (appearance 376), which classifies human
//     because the row is shared with Basic-voiced Sith soldiers/rogues (see
//     the build/dump-2da NOTE). But Vek himself — the Manaan Ahto East swoop
//     handler — is voiced in alien Twi'leki, not Basic, so his subtitle is the
//     player's only channel. The shared appearance row can't be flipped
//     without un-suppressing the Sith mooks, so Vek is exempted by tag.
//     (Reported in-game 2026-06-10; supersedes the 2026-06-09 model-only
//     verification that assumed every 376 wearer was Basic-voiced.)
//   - "tat17_03komad_01": Komad Fortuna, the hunter-guild member outside
//     Anchorhead (Tatooine, module tat17). Wears appearance 445, which
//     classifies human, but he is a Twi'lek voiced in alien Twi'leki, so his
//     translated subtitle is the player's only channel. Same case as Vek.
//     (Reported in-game 2026-06-15.)
//   - "kas22_xkomad_01": the same Komad Fortuna, reappearing on Kashyyyk
//     (module kas22 — he references his earlier Tatooine hunt in dialogue).
//     Same appearance 445, same alien-Twi'leki voice, but a different tag, so
//     the Tatooine exemption above doesn't catch him. (Reported in-game
//     2026-06-17.)
constexpr const char* kNeverSuppressTags[] = {
    "sasha",
    "vek",
    "tat17_03komad_01",
    "kas22_xkomad_01",
};

bool IsNeverSuppressTag(const char* tag) {
    if (!tag || !tag[0]) return false;
    for (const char* t : kNeverSuppressTags) {
        if (_stricmp(t, tag) == 0) return true;
    }
    return false;
}

// Per-tag always-suppress list — the mirror image of kNeverSuppressTags.
// These speakers classify as non-human/non-droid by appearance and race (so
// the rule below would speak their subtitle), but they are in fact voiced in
// Basic with full VO, so the subtitle is redundant and clashes with the voice.
// The shared appearance row can't be flipped without un-suppressing the
// genuinely alien crowd that wears the same model. Matched case-insensitively
// on CSWSObject.tag.
//
//   - "man26_casandra": wears Alien_Twilek_Female_02 (appearance 270), which
//     classifies non-human because the row is otherwise the alien Twi'lek
//     dancer/crowd model. But Cassandra (Manaan Ahto East) speaks Basic with
//     full VO, so her subtitle clashed with the voice. Suppress by tag.
//     (Reported in-game 2026-06-11; inverse of the Vek case above.)
//   - "man28_merc": the surviving Republic mercenary barricaded in the Hrakert
//     Rift station (Manaan, module 28). Wears appearance 269, which classifies
//     non-human, but he is human (race == HUMAN) and voiced in Basic with full
//     VO, so his subtitle is redundant and clashed with the voice. Same case as
//     Cassandra. (Reported in-game 2026-06-14.)
constexpr const char* kAlwaysSuppressTags[] = {
    "man26_casandra",
    "man28_merc",
};

bool IsAlwaysSuppressTag(const char* tag) {
    if (!tag || !tag[0]) return false;
    for (const char* t : kAlwaysSuppressTags) {
        if (_stricmp(t, tag) == 0) return true;
    }
    return false;
}

// True iff this speaker's subtitle is redundant given the VO, so we suppress
// it under the (shared) HumanSubtitles toggle. Two cases:
//   - human-appearance speakers: intelligible Basic VO the player already
//     understands (the original criterion — includes Basic-voiced non-humans
//     like Mission/Juhani, see IsHumanAppearance note above);
//   - droids (race == DROID): either intelligible Basic VO (HK-47) or pure
//     beep onomatopoeia whose subtitle carries no meaning (T3-M4, generic
//     droids — the conveyed meaning lives in the player's reply choices,
//     which are narrated separately). Verified from dialog.tlk 2026-06-05.
// Genuinely alien speakers (Twi'lek crowd, Wookiee) are neither, so their
// subtitle stays the player's only channel and is always spoken. The two
// per-tag lists override the appearance/race verdict for individual characters
// misclassified by their shared model: never-suppress forces speech on (Sasha,
// Vek), always-suppress forces it off (Cassandra). Never-suppress wins ties —
// the safe direction is to keep speech on.
bool IsSuppressibleSpeaker(const SpeakerInfo& info) {
    if (IsNeverSuppressTag(info.tag)) return false;
    if (IsAlwaysSuppressTag(info.tag)) return true;
    return IsHumanAppearance(info.appearance) || info.raceEnum == kRaceDroid;
}

// ---- Skill-check outcome marker ------------------------------------------
//
// Persuade / Computer-Use / Repair etc. results are authored as ordinary NPC
// entry nodes whose subtitle text *begins* with a localized bracketed marker:
//   DE [Erfolg] / [Fehlschlag] / [GESCHEITERT]   EN [Success] / [Failure]
//   FR [Succ\xE8s] / [R\xE9ussite] / [\xC9chec]   IT [Successo] / [Fallimento]
//   ES [\xC9xito] / [Fracaso] / [Fallo]
// plus UPPERCASE terminal variants, trailing "!" / leading "\xA1", and
// compound forms like [\xDCberreden: Fehlschlag!] / [COMPUTER SKILL: Success!]
// / [Failure: Insufficient Spikes]. (All five forms verified against each
// locale's dialog.tlk, 2026-06-09.)
//
// When such a line is VO-suppressed the whole subtitle — marker included —
// goes silent, so the player never learns whether the check passed. We detect
// the leading bracket token and, if it denotes a check outcome, speak just
// that token (never the suppressed speech that follows the "]").
//
// Locale-robust by construction: the token is accent-folded to lowercase
// ASCII and substring-matched against a flat multilingual set of outcome
// roots, so the same code fires on every official locale (EFIGS) — and on the
// occasional cross-locale stray (an English "[Failure]" is baked into the
// German TLK) — with no language detection. Anything that isn't an outcome
// marker (skill-only tags like [\xDCberreden], stage directions like [lacht])
// contains no root and stays silent, so a suppressed line is never partially
// leaked.

// Fold one CP1252 byte (CExoString encoding) to lowercase ASCII for matching.
// Only e-acute/grave/circ/diaeresis are mapped, the only accents that occur in
// the outcome roots; every other byte passes through, which is fine for a
// substring search.
char FoldByte(unsigned char c) {
    if (c >= 'A' && c <= 'Z') return static_cast<char>(c + 32);
    switch (c) {
        case 0xC8: case 0xC9: case 0xCA: case 0xCB:   // \xC8\xC9\xCA\xCB
        case 0xE8: case 0xE9: case 0xEA: case 0xEB:   // \xE8\xE9\xEA\xEB
            return 'e';
        default:
            return static_cast<char>(c);
    }
}

// If `line` opens with a bracketed skill-check outcome marker, copy the
// marker's inner text (verbatim, brackets removed, leading "\xA1" and trailing
// whitespace trimmed) into `out` and return true. Otherwise return false.
bool ExtractSkillCheckMarker(const char* line, char* out, size_t outSize) {
    if (!line || !out || outSize < 2) return false;
    const unsigned char* p = reinterpret_cast<const unsigned char*>(line);
    while (*p == ' ' || *p == '\t') ++p;
    if (*p != '[') return false;
    ++p;  // past '['

    char inner[80];
    char folded[80];
    size_t n = 0;
    while (p[n] && p[n] != ']' && n < sizeof(inner) - 1) {
        inner[n]  = static_cast<char>(p[n]);
        folded[n] = FoldByte(p[n]);
        ++n;
    }
    if (p[n] != ']' || n == 0) return false;  // no close bracket, or empty/over-long
    inner[n]  = '\0';
    folded[n] = '\0';

    // "succe" covers success/Succ\xE8s/Successo/truncated SUCC\xC8; "gescheiter"
    // covers the uppercase German terminal "GESCHEITERT"; "falliment" covers
    // Fallimento + UPPERCASE. A flat union — direction (success vs failure) is
    // irrelevant: any match means "speak this marker".
    static const char* kOutcomeRoots[] = {
        "erfolg", "succe", "reussit", "exito",            // success
        "fehlschlag", "gescheiter", "failure", "echec",   // failure
        "falliment", "fracaso", "fallo",
    };
    bool isMarker = false;
    for (const char* r : kOutcomeRoots) {
        if (std::strstr(folded, r)) { isMarker = true; break; }
    }
    if (!isMarker) return false;

    char* s = inner;
    if (static_cast<unsigned char>(s[0]) == 0xA1) ++s;  // drop leading "\xA1"
    size_t len = std::strlen(s);
    while (len && (s[len - 1] == ' ' || s[len - 1] == '\t')) s[--len] = '\0';
    std::strncpy(out, s, outSize - 1);
    out[outSize - 1] = '\0';
    return out[0] != '\0';
}

// Given a candidate server object, validate it's a creature and fill the
// tag / race / appearance fields. Returns false (leaving out.speaker null)
// if the object is null, isn't a creature, or a read faults.
bool FillSpeakerFromServerObject(void* partner, SpeakerInfo& out) {
    if (!partner) return false;
    __try {
        int kind = acc::engine::GetObjectKind(partner);
        if (kind != static_cast<int>(acc::engine::GameObjectKind::Creature)) {
            return false;
        }

        out.speaker = partner;
        auto* partnerBytes = reinterpret_cast<unsigned char*>(partner);

        // Tag — CExoString at CSWSObject +0x18. ReadCExoString handles the
        // inline / heap-buffer distinction; empty tag → out.tag stays "".
        acc::engine::ReadCExoString(partner, kObjectTagOffset,
                                    out.tag, sizeof(out.tag));

        // Race + appearance_type via stats pointer. The inline cache on
        // CSWSCreature at +0xa4c reads 0 even for fully-initialised
        // speakers, so we always go through stats.
        void* stats = *reinterpret_cast<void**>(
            partnerBytes + kCreatureStatsPointerOffset);
        if (stats) {
            auto* sb = reinterpret_cast<unsigned char*>(stats);
            out.raceEnum   = *reinterpret_cast<unsigned short*>(
                sb + kCreatureStatsRaceOffset);
            out.appearance = *reinterpret_cast<unsigned short*>(
                sb + kCreatureStatsAppearanceTypeOffset);
        }
    } __except (EXCEPTION_EXECUTE_HANDLER) {
        out.speaker = nullptr;
        return false;
    }
    return out.speaker != nullptr;
}

// Read CGuiInGame+0x170 — the current dialog entry's speaker as a CLIENT
// object id. 0x7f000000 / 0 mean "no participant". See engine_offsets.h.
uint32_t ReadGuiDialogSpeakerClientId() {
    void* gui = acc::engine::ResolveGuiInGame();
    if (!gui) return 0x7F000000u;
    __try {
        return *reinterpret_cast<uint32_t*>(
            reinterpret_cast<unsigned char*>(gui) +
            kCGuiInGameDialogSpeakerOffset);
    } __except (EXCEPTION_EXECUTE_HANDLER) {
        return 0x7F000000u;
    }
}

bool ResolveDialogSpeaker(SpeakerInfo& out) {
    out.speaker    = nullptr;
    out.appearance = -1;
    out.raceEnum   = 0;
    out.tag[0]     = '\0';

    // PRIMARY: the GUI's per-line speaker (client id → server object). This
    // is the only path that names the speaker in overheard NPC-to-NPC
    // scenes, where the player isn't a conversation participant.
    uint32_t clientId = ReadGuiDialogSpeakerClientId();
    if (clientId != 0 && clientId != 0x7F000000u) {
        uint32_t serverId = acc::engine::ClientToServerObjectId(clientId);
        if (serverId != 0 && serverId != 0x7F000000u) {
            void* partner = acc::engine::ResolveServerObjectHandle(serverId);
            if (FillSpeakerFromServerObject(partner, out)) return true;
        }
    }

    // FALLBACK: the player's own conversation partner (server id at +0x54).
    // Correct for 1-on-1 dialog and player-involved barks; used only when
    // the GUI field is unavailable (e.g. bark bubbles, pre-entry ticks).
    void* player = acc::engine::GetPlayerServerCreature();
    if (!player) return false;

    uint32_t partnerHandle = 0;
    __try {
        // +0x54 is a HANDLE (ulong), not a CSWSObject* — Lane's struct
        // label is misleading. Verified live 2026-05-30: values were
        // 0x0D / 0xC2 (server-side handle IDs, not pointers).
        partnerHandle = *reinterpret_cast<uint32_t*>(
            reinterpret_cast<unsigned char*>(player) +
            kServerObjectDialogOwnerOffset);
    } __except (EXCEPTION_EXECUTE_HANDLER) {
        return false;
    }
    if (partnerHandle == 0 || partnerHandle == 0x7F000000u) return false;

    void* partner = acc::engine::ResolveServerObjectHandle(partnerHandle);
    return FillSpeakerFromServerObject(partner, out);
}

// Resolve the speaker of a bark bubble from its own owner field, rather than
// the dialog-speaker chain (which is empty for barks — see ResolveDialogSpeaker
// note above, where bark resolution always failed and every bark was spoken).
//
// CSWGuiBarkBubble.object_id @+0x1c0 holds the speaker's CLIENT object id
// (CSWGuiBarkBubble::SetBark). Sentinel 0x7f000000 / 0 means the bark has no
// owning creature — system/loudspeaker feedback like the Ahto City camera-zone
// messages — so we leave out.speaker null and the caller speaks it. A real id
// converts client → server → CSWSObject* exactly like the dialog path, so we
// can classify the bark's speaker by appearance/race and honour the toggle.
//
// Returns false (speak the bark) on sentinel owner or any resolution failure.
bool ResolveBarkSpeaker(void* barkPanel, SpeakerInfo& out) {
    out.speaker    = nullptr;
    out.appearance = -1;
    out.raceEnum   = 0;
    out.tag[0]     = '\0';
    if (!barkPanel) return false;

    uint32_t clientId;
    __try {
        clientId = *reinterpret_cast<uint32_t*>(
            reinterpret_cast<unsigned char*>(barkPanel) +
            kBarkBubbleObjectIdOffset);
    } __except (EXCEPTION_EXECUTE_HANDLER) {
        return false;
    }
    if (clientId == 0 || clientId == 0x7F000000u) return false;

    uint32_t serverId = acc::engine::ClientToServerObjectId(clientId);
    if (serverId == 0 || serverId == 0x7F000000u) return false;

    void* speaker = acc::engine::ResolveServerObjectHandle(serverId);
    return FillSpeakerFromServerObject(speaker, out);
}

// ---- Suppression decision ------------------------------------------------
//
// True iff the engine's currently playing the line in player-language VO
// AND the user has asked us not to read those subtitles. We resolve the
// speaker, classify by appearance, and check the toggle. Conservative: any
// resolution failure / unknown appearance returns false (speak the line).
bool ShouldSuppressNpcLine() {
    if (acc::menus::modsettings::GetToggle(
            acc::menus::modsettings::Option::HumanSubtitles)) {
        return false;  // toggle ON = user wants human subtitles spoken
    }
    SpeakerInfo info;
    if (!ResolveDialogSpeaker(info)) return false;
    return IsSuppressibleSpeaker(info);
}

// Find the foreground active dialog panel — first match for any of the
// dialog kinds. Returns the panel pointer + which kind matched.
struct DialogPanelMatch {
    void*                 panel;
    acc::engine::PanelKind kind;
};

DialogPanelMatch FindActiveDialogPanel() {
    DialogPanelMatch out{nullptr, acc::engine::PanelKind::Unknown};
    void* mgr = *reinterpret_cast<void**>(kAddrGuiManagerPtr);
    if (!mgr) return out;
    auto* base = reinterpret_cast<unsigned char*>(mgr);
    int   panelCount = *reinterpret_cast<int*>(base + kMgrPanelsSizeOffset);
    void** panelData = *reinterpret_cast<void***>(base + kMgrPanelsDataOffset);
    if (!panelData || panelCount <= 0) return out;
    int n = panelCount > 16 ? 16 : panelCount;
    for (int i = 0; i < n; ++i) {
        void* p = panelData[i];
        if (!p) continue;
        auto k = acc::engine::IdentifyPanel(p);
        switch (k) {
        case acc::engine::PanelKind::DialogCinematic:
        case acc::engine::PanelKind::DialogCinematicCopy:
        case acc::engine::PanelKind::DialogComputer:
        case acc::engine::PanelKind::DialogComputerCamera:
            out.panel = p;
            out.kind  = k;
            return out;
        default:
            break;
        }
    }
    return out;
}

// Find a BarkBubble panel (independent lifecycle from main dialog).
void* FindBarkBubblePanel() {
    void* mgr = *reinterpret_cast<void**>(kAddrGuiManagerPtr);
    if (!mgr) return nullptr;
    auto* base = reinterpret_cast<unsigned char*>(mgr);
    int   panelCount = *reinterpret_cast<int*>(base + kMgrPanelsSizeOffset);
    void** panelData = *reinterpret_cast<void***>(base + kMgrPanelsDataOffset);
    if (!panelData || panelCount <= 0) return nullptr;
    int n = panelCount > 16 ? 16 : panelCount;
    for (int i = 0; i < n; ++i) {
        void* p = panelData[i];
        if (!p) continue;
        if (acc::engine::IdentifyPanel(p) ==
            acc::engine::PanelKind::BarkBubble) {
            return p;
        }
    }
    return nullptr;
}

// Read row count of a CSWGuiListBox at panel + offset.
int ReadListBoxRowCount(void* panel, size_t lbOffset) {
    if (!panel) return 0;
    __try {
        void* lb = reinterpret_cast<unsigned char*>(panel) + lbOffset;
        auto* lbList = reinterpret_cast<CExoArrayList*>(
            reinterpret_cast<unsigned char*>(lb) +
            kListBoxControlsOffset);
        if (!lbList || !lbList->data) return 0;
        return lbList->size;
    } __except (EXCEPTION_EXECUTE_HANDLER) {
        return 0;
    }
}

// Walk a panel's controls[] for the first child whose text resolves
// non-empty. Used as a fallback for the BarkBubble — its label offset
// isn't documented in the plan, but the panel renders a single visible
// text label which reads via FromControl.
bool ReadFirstVisibleText(void* panel, char* outBuf, size_t bufSize) {
    if (!panel || !outBuf || bufSize < 2) return false;
    outBuf[0] = '\0';
    __try {
        auto* base = reinterpret_cast<unsigned char*>(panel);
        auto* controls = reinterpret_cast<CExoArrayList*>(
            base + kPanelControlsOffset);
        if (!controls || !controls->data) return false;
        int sz = controls->size > 16 ? 16 : controls->size;
        for (int i = 0; i < sz; ++i) {
            void* child = controls->data[i];
            if (!child) continue;
            if (acc::menus::extract::FromControl(child, outBuf, bufSize) &&
                outBuf[0] != '\0') {
                return true;
            }
        }
    } __except (EXCEPTION_EXECUTE_HANDLER) {
        outBuf[0] = '\0';
    }
    return false;
}

}  // namespace

void Tick() {
    // Module-load latch — FindActiveDialogPanel walks the manager's
    // panels[] which the engine is tearing down mid-handoff during a
    // cutscene transition. See transitions.h IsModuleLoadPending.
    if (acc::transitions::IsModuleLoadPending()) return;

    // ---- NPC line + replies count for the main dialog panel. ----
    DialogPanelMatch m = FindActiveDialogPanel();
    static void*       s_lastPanel    = nullptr;
    static char        s_lastNpcLine[512] = {0};

    if (!m.panel) {
        if (s_lastPanel) {
            acclog::Write("Dialog.Speech", "panel closed");
            s_lastPanel = nullptr;
            s_lastNpcLine[0] = '\0';
            // A Trask Q&A branch (e.g. "Wie kann ich Türen öffnen?") can record
            // its keyboard hint and then return straight to the world with no
            // further reply break — so the reply-break trigger in
            // MonitorDialogReplies never flushed it. Flush on dialogue close so
            // the recap popup still fires. Idempotent: no-ops if nothing pending
            // or a popup is already up (it fired at an earlier reply break).
            acc::tutorial_popup::FirePendingAtReplyBreak();
        }
    } else {
        // First sight — set baseline silently. Don't replay history on
        // open; the very first NPC line will trigger via the diff path
        // on the next tick when the engine populates the message label.
        if (s_lastPanel != m.panel) {
            s_lastPanel = m.panel;
            s_lastNpcLine[0] = '\0';
        }

        char npc[512] = "";
        bool gotNpc = acc::engine::ReadLabelTextAt(m.panel, kDialogMessageLabelOffset,
                                    npc, sizeof(npc));
        if (gotNpc && std::strcmp(npc, s_lastNpcLine) != 0) {
            // Rewritten tutorial line (Trask / pop): keep it suppressed during
            // his Basic VO, but remember its keyboard hint + source strref so
            // the reply-prompt monitor can pop a real tutorial window with it
            // once he's finished speaking. Recorded regardless of suppression.
            uint32_t tutStrref = 0;
            if (const char* tutHint =
                    acc::tutorial_hints::HintForDialogLine(npc, &tutStrref)) {
                acc::tutorial_popup::RecordPendingHint(tutStrref, tutHint);
            }

            // Per-line speaker classification: log race + appearance even
            // when we end up speaking, so future override decisions can
            // be made on real (speaker tag, race, appearance_type) data.
            SpeakerInfo info;
            bool resolved     = ResolveDialogSpeaker(info);
            bool suppressible = resolved && IsSuppressibleSpeaker(info);
            bool suppress = suppressible && !acc::menus::modsettings::GetToggle(
                acc::menus::modsettings::Option::HumanSubtitles);

            // When suppressing, still surface a leading skill-check outcome
            // marker ([Erfolg]/[Fehlschlag] etc.) so a Persuade/Computer/Repair
            // result reaches the player without the redundant Basic VO line.
            char marker[80] = "";
            bool spokeMarker = false;
            if (!suppress) {
                prism::Speak(npc, /*interrupt=*/true);
            } else if (ExtractSkillCheckMarker(npc, marker, sizeof(marker))) {
                prism::Speak(marker, /*interrupt=*/true);
                spokeMarker = true;
            }
            acclog::Write("Dialog.Speech",
                          "NPC line panel=%p kind=%s speaker=[%s] "
                          "appearance=%d race=%d suppressible=%d suppress=%d "
                          "marker=[%s] -> [%.300s]",
                          m.panel, acc::engine::PanelKindName(m.kind),
                          resolved ? info.tag : "?",
                          info.appearance, info.raceEnum,
                          suppressible ? 1 : 0, suppress ? 1 : 0,
                          spokeMarker ? marker : "", npc);
            std::strncpy(s_lastNpcLine, npc, sizeof(s_lastNpcLine) - 1);
            s_lastNpcLine[sizeof(s_lastNpcLine) - 1] = '\0';
        }

        // For Computer dialog variant, also speak the message_listbox
        // (terminal output) when its row count grows.
        if (m.kind == acc::engine::PanelKind::DialogComputer ||
            m.kind == acc::engine::PanelKind::DialogComputerCamera) {
            static int s_lastComputerRows = 0;
            int rows = ReadListBoxRowCount(m.panel,
                                           kDialogComputerMessageListBoxOffset);
            if (rows > s_lastComputerRows) {
                // Speak each newly appended terminal line.
                __try {
                    void* lb = reinterpret_cast<unsigned char*>(m.panel) +
                               kDialogComputerMessageListBoxOffset;
                    auto* lbList = reinterpret_cast<CExoArrayList*>(
                        reinterpret_cast<unsigned char*>(lb) +
                        kListBoxControlsOffset);
                    if (lbList && lbList->data) {
                        int cap = rows > lbList->size ? lbList->size : rows;
                        for (int i = s_lastComputerRows;
                             i < cap; ++i) {
                            void* row = lbList->data[i];
                            if (!row) continue;
                            char text[512];
                            if (acc::menus::extract::FromControl(
                                    row, text, sizeof(text)) &&
                                text[0] != '\0') {
                                prism::Speak(text, /*interrupt=*/false);
                                acclog::Write("Dialog.Speech",
                                              "computer row %d [%.200s]",
                                              i, text);
                            }
                        }
                    }
                } __except (EXCEPTION_EXECUTE_HANDLER) {
                    // ignore — try again next tick
                }
            }
            if (rows < s_lastComputerRows) {
                // Reset on shrink (panel cleared).
                acclog::Write("Dialog.Speech",
                              "computer rows reset %d -> %d",
                              s_lastComputerRows, rows);
            }
            s_lastComputerRows = rows;
        }

        // ---- R — re-speak the current NPC line on demand. ----
        // Gated on a dialog panel being foreground (we're inside the active
        // branch). Repeats the last captured line verbatim, even if it was
        // VO-suppressed — pressing R is an explicit "say it again" request,
        // so the suppression toggle doesn't apply here.
        if (acc::hotkeys::Pressed(acc::hotkeys::Action::DialogRepeatLine) &&
            s_lastNpcLine[0] != '\0') {
            prism::Speak(s_lastNpcLine, /*interrupt=*/true);
            acclog::Write("Dialog.Speech", "R repeat -> [%.300s]", s_lastNpcLine);
        }
    }

    // ---- BarkBubble — independent lifecycle. ----
    void* bark = FindBarkBubblePanel();
    static void* s_lastBark = nullptr;
    static char  s_lastBarkText[512] = {0};
    if (!bark) {
        if (s_lastBark) {
            acclog::Write("Dialog.Speech", "bark closed");
            s_lastBark = nullptr;
            s_lastBarkText[0] = '\0';
        }
    } else {
        char text[512] = "";
        ReadFirstVisibleText(bark, text, sizeof(text));
        if (text[0] != '\0' && std::strcmp(text, s_lastBarkText) != 0) {
            // Barks carry their own speaker: CSWGuiBarkBubble.object_id names
            // the owning creature (client id). Ownerless barks (system /
            // loudspeaker feedback) resolve false and stay spoken; a human or
            // droid owner classifies the same way dialog does, so barks now
            // honour the HumanSubtitles toggle instead of always speaking.
            SpeakerInfo info;
            bool resolved     = ResolveBarkSpeaker(bark, info);
            bool suppressible = resolved && IsSuppressibleSpeaker(info);
            bool suppress = suppressible && !acc::menus::modsettings::GetToggle(
                acc::menus::modsettings::Option::HumanSubtitles);

            if (!suppress) {
                prism::Speak(text, /*interrupt=*/false);
            }
            acclog::Write("Dialog.Speech",
                          "bark panel=%p speaker=[%s] appearance=%d race=%d "
                          "suppressible=%d suppress=%d -> [%.300s]",
                          bark, resolved ? info.tag : "?",
                          info.appearance, info.raceEnum,
                          suppressible ? 1 : 0, suppress ? 1 : 0, text);
            std::strncpy(s_lastBarkText, text, sizeof(s_lastBarkText) - 1);
            s_lastBarkText[sizeof(s_lastBarkText) - 1] = '\0';
        }
        s_lastBark = bark;
    }
}

}  // namespace acc::dialog_speech
