#include "engine_rebase.h"

#include <windows.h>

namespace acc::addr {

namespace {

struct Entry {
    uintptr_t reference;
    uintptr_t target;
};

// Generated by `kdev sigscan`, sorted ascending by reference address.
constexpr Entry kTable[] = {
#include "engine_rebase_table.inc"
};

constexpr size_t kTableCount = sizeof(kTable) / sizeof(kTable[0]);

// .rdata map — vtables and the two data pointers beside them. Separate from the
// generated .text table because `kdev sigscan` cannot yet resolve .rdata: there
// is no code at these addresses to take a signature from.
//
// Stage 2 skipped .rdata on the belief that we held no bare .rdata constants,
// only vtable references inside functions. That was wrong — 44 of them, and on
// a rebased build every vtable-identity check silently failed, which is how the
// character-creation screen ended up reading its class buttons as "control 11".
//
// Resolved 2026-07-25 by two independent methods that had to agree:
//   * operand cross-reference — the address appears in .text as an imm32 (the
//     constructor storing the vtable); locate that code in the target with
//     operands masked and read the new value;
//   * vtable content verification — walk a candidate's first entries and compare
//     the *functions* they point at byte-for-byte. Only real vtables qualify,
//     which is why the import-table entry and the upgrade-slot table resolved by
//     operand alone.
// 23 resolved by both, 19 by content, 2 by operand; no disagreements.
constexpr Entry kRdataTable[] = {
#include "engine_rebase_rdata.inc"
};

constexpr size_t kRdataCount = sizeof(kRdataTable) / sizeof(kRdataTable[0]);

// Hand-resolved supplement. `kdev sigscan` cannot place these two by their own
// bytes, so they are NOT in the generated table and must live here — putting
// them in the .inc would lose them on the next regeneration.
//
// Both were resolved by cross-reference (2026-07-25): find every `call rel32`
// to the address in the reference, locate each call site in the target by its
// surrounding bytes, and decode the displacement there. Every call site agreed,
// and the bytes at the resolved address then matched the reference.
//
//   CExoInput::SetActive — one of a run of identical 8-byte forwarding thunks
//   (`mov ecx,[ecx+4]; jmp internal`), so its own signature matches a dozen
//   siblings. 10 of 12 call sites resolved, unanimous; the other two sat in
//   code whose window wasn't unique enough to place, and neither dissented.
//
//   CSWCMapPin::CSWCMapPin — has a near-twin that shares its whole prologue.
//   3 of 3 call sites agreed on 0x00692430; the twin (0x005fcca0) diverges 30
//   bytes in, which is what rules it out.
constexpr Entry kXrefTable[] = {
    { 0x005DF540, 0x005DF710 },  // kAddrCExoInputSetActive
    { 0x00692540, 0x00692430 },  // kAddrCSWCMapPinCtor
};

constexpr size_t kXrefCount = sizeof(kXrefTable) / sizeof(kXrefTable[0]);

// PE link timestamps identify the build. The reference (Steam/GoG 1.0.3) is
// 2004-02-12 18:15:53Z; Allard 1.72 ships a 2004-03-05 00:43:51Z build. Reading
// the timestamp costs one header walk of our own image and, unlike hashing the
// file, needs no I/O — so it is safe from a static initialiser.
constexpr uint32_t kTimestampReference = 0x402BC2D9;  // 1076609753, 2004-02-12 18:15:53Z
constexpr uint32_t kTimestampAllard172 = 0x4047CD47;  // 1078447431, 2004-03-05 00:43:51Z

enum class Build { Reference, Allard172, Unknown };

uint32_t ReadOwnLinkTimestamp() {
    // GetModuleHandle(nullptr) is the exe, not this DLL — the addresses we
    // rebase are the game's, so the game's image is what must be identified.
    auto base = reinterpret_cast<const uint8_t*>(GetModuleHandleW(nullptr));
    if (!base) return 0;

    // Deliberately defensive: this runs before anything else has validated the
    // image, and a bad read here would fault during static init, which is
    // painful to diagnose.
    if (base[0] != 'M' || base[1] != 'Z') return 0;
    int32_t lfanew = *reinterpret_cast<const int32_t*>(base + 0x3C);
    if (lfanew <= 0 || lfanew > 0x1000) return 0;
    const uint8_t* pe = base + lfanew;
    if (pe[0] != 'P' || pe[1] != 'E' || pe[2] != 0 || pe[3] != 0) return 0;
    return *reinterpret_cast<const uint32_t*>(pe + 8);
}

Build DetectBuild() {
    switch (ReadOwnLinkTimestamp()) {
        case kTimestampReference: return Build::Reference;
        case kTimestampAllard172: return Build::Allard172;
        default:                  return Build::Unknown;
    }
}

// Function-local static: initialised on first use, thread-safe under the C++11
// magic-statics rule, and with no dependency on any other global's
// initialisation order. That last part is the point — the constants that call
// R() are themselves dynamically initialised at load time, in unspecified
// order across translation units.
Build CurrentBuild() {
    static const Build b = DetectBuild();
    return b;
}

}  // namespace

uintptr_t R(uintptr_t referenceVa) {
    if (CurrentBuild() != Build::Allard172) {
        // Reference build, or a build we do not know. An unknown build cannot
        // be rebased, and the version gate should have refused it long before
        // this point, so pass the value through unchanged.
        return referenceVa;
    }

    size_t lo = 0;
    size_t hi = kTableCount;
    while (lo < hi) {
        size_t mid = lo + (hi - lo) / 2;
        if (kTable[mid].reference < referenceVa) {
            lo = mid + 1;
        } else if (kTable[mid].reference > referenceVa) {
            hi = mid;
        } else {
            return kTable[mid].target;
        }
    }
    // Not in the generated .text table — try the .rdata map (also sorted).
    lo = 0;
    hi = kRdataCount;
    while (lo < hi) {
        size_t mid = lo + (hi - lo) / 2;
        if (kRdataTable[mid].reference < referenceVa) {
            lo = mid + 1;
        } else if (kRdataTable[mid].reference > referenceVa) {
            hi = mid;
        } else {
            return kRdataTable[mid].target;
        }
    }

    // Then the hand-resolved supplement. Linear, because it holds two entries.
    for (size_t i = 0; i < kXrefCount; ++i) {
        if (kXrefTable[i].reference == referenceVa) return kXrefTable[i].target;
    }

    // Known build, unmapped address. See the header: 0 faults recognisably,
    // a stale address corrupts silently.
    return 0;
}

bool IsRebased() { return CurrentBuild() == Build::Allard172; }

const char* ActiveBuildName() {
    switch (CurrentBuild()) {
        case Build::Reference: return "reference";
        case Build::Allard172: return "allard-1.72";
        default:               return "unknown";
    }
}

}  // namespace acc::addr
