#include "engine_rebase.h"

#include "engine_game.h"

namespace acc::addr {

namespace {

struct Entry {
    uintptr_t reference;
    uintptr_t target;
};

// Generated by `kdev sigscan`, sorted ascending by reference address.
constexpr Entry kTable[] = {
#include "engine_rebase_table.inc"
};

constexpr size_t kTableCount = sizeof(kTable) / sizeof(kTable[0]);

// .rdata map — vtables and the two data pointers beside them. Separate from the
// generated .text table because `kdev sigscan` cannot yet resolve .rdata: there
// is no code at these addresses to take a signature from.
//
// Stage 2 skipped .rdata on the belief that we held no bare .rdata constants,
// only vtable references inside functions. That was wrong — 44 of them, and on
// a rebased build every vtable-identity check silently failed, which is how the
// character-creation screen ended up reading its class buttons as "control 11".
//
// Resolved 2026-07-25 by two independent methods that had to agree:
//   * operand cross-reference — the address appears in .text as an imm32 (the
//     constructor storing the vtable); locate that code in the target with
//     operands masked and read the new value;
//   * vtable content verification — walk a candidate's first entries and compare
//     the *functions* they point at byte-for-byte. Only real vtables qualify,
//     which is why the import-table entry and the upgrade-slot table resolved by
//     operand alone.
// 23 resolved by both, 19 by content, 2 by operand; no disagreements.
constexpr Entry kRdataTable[] = {
#include "engine_rebase_rdata.inc"
};

constexpr size_t kRdataCount = sizeof(kRdataTable) / sizeof(kRdataTable[0]);

// Hand-resolved supplement. `kdev sigscan` cannot place these two by their own
// bytes, so they are NOT in the generated table and must live here — putting
// them in the .inc would lose them on the next regeneration.
//
// Both were resolved by cross-reference (2026-07-25): find every `call rel32`
// to the address in the reference, locate each call site in the target by its
// surrounding bytes, and decode the displacement there. Every call site agreed,
// and the bytes at the resolved address then matched the reference.
//
//   CExoInput::SetActive — one of a run of identical 8-byte forwarding thunks
//   (`mov ecx,[ecx+4]; jmp internal`), so its own signature matches a dozen
//   siblings. 10 of 12 call sites resolved, unanimous; the other two sat in
//   code whose window wasn't unique enough to place, and neither dissented.
//
//   CSWCMapPin::CSWCMapPin — has a near-twin that shares its whole prologue.
//   3 of 3 call sites agreed on 0x00692430; the twin (0x005fcca0) diverges 30
//   bytes in, which is what rules it out.
//
// The `kdev-sigscan: ignore` markers keep the harvester off these lines: the
// right-hand column is a relink address, which is meaningless in the reference
// build and would be scanned as if it were one. Both left-hand values are
// harvested from their real declarations instead (engine_input.cpp:23 and
// engine_area.h:404), so nothing is lost by skipping the pair here.
constexpr Entry kXrefTable[] = {
    { 0x005DF540, 0x005DF710 },  // kAddrCExoInputSetActive  kdev-sigscan: ignore
    { 0x00692540, 0x00692430 },  // kAddrCSWCMapPinCtor      kdev-sigscan: ignore
};

constexpr size_t kXrefCount = sizeof(kXrefTable) / sizeof(kXrefTable[0]);

}  // namespace

uintptr_t R(uintptr_t referenceVa) {
    switch (acc::game::CurrentBuild()) {
        case acc::game::Build::Kotor1Relink2004:
            break;  // the one build this function maps; fall through to lookup

        case acc::game::Build::Kotor2Aspyr2015:
            // A DIFFERENT GAME. Every address in this codebase is a KOTOR 1
            // address, and KOTOR 2 is an Aspyr recompile, not a relink — the
            // functions were re-emitted, not moved, so no reference value is
            // meaningful here and no table maps them yet. Returning
            // `referenceVa` (what an unrecognised build gets) would hand out
            // K1 addresses pointing into unrelated K2 code: a silent jump into
            // the middle of some other function.
            //
            // 0 instead. It faults recognisably at address 0, and the ~12 call
            // sites already wrapped in acc::addr::Ok() degrade gracefully
            // without changes. Everything else must be gated on
            // acc::game::IsKotor1() before it runs — that gating, not this
            // return, is what makes KOTOR 2 safe.
            return 0;

        case acc::game::Build::Kotor1Reference:
        case acc::game::Build::Unknown:
        default:
            // The reference build maps to itself. An unknown build cannot be
            // rebased and the version gate should have refused it long before
            // this point, so it keeps the pre-existing pass-through.
            return referenceVa;
    }

    size_t lo = 0;
    size_t hi = kTableCount;
    while (lo < hi) {
        size_t mid = lo + (hi - lo) / 2;
        if (kTable[mid].reference < referenceVa) {
            lo = mid + 1;
        } else if (kTable[mid].reference > referenceVa) {
            hi = mid;
        } else {
            return kTable[mid].target;
        }
    }
    // Not in the generated .text table — try the .rdata map (also sorted).
    lo = 0;
    hi = kRdataCount;
    while (lo < hi) {
        size_t mid = lo + (hi - lo) / 2;
        if (kRdataTable[mid].reference < referenceVa) {
            lo = mid + 1;
        } else if (kRdataTable[mid].reference > referenceVa) {
            hi = mid;
        } else {
            return kRdataTable[mid].target;
        }
    }

    // Then the hand-resolved supplement. Linear, because it holds two entries.
    for (size_t i = 0; i < kXrefCount; ++i) {
        if (kXrefTable[i].reference == referenceVa) return kXrefTable[i].target;
    }

    // Known build, unmapped address. See the header: 0 faults recognisably,
    // a stale address corrupts silently.
    return 0;
}

uintptr_t Pick(uintptr_t referenceVa, uintptr_t kotor2Va) {
    if (acc::game::IsKotor2()) return kotor2Va;
    return R(referenceVa);
}

uintptr_t PickGlobal(uintptr_t kotor1Va, uintptr_t kotor2Va) {
    // Deliberately not R(): .data is byte-stable across the KOTOR 1 builds and
    // is not in R()'s table, so routing it there would zero it on the relink.
    return acc::game::IsKotor2() ? kotor2Va : kotor1Va;
}

uintptr_t Kotor1Only(uintptr_t referenceVa) {
    // Same run-time behaviour as a bare R() — 0 on KOTOR 2. Distinct only so
    // that "checked, and KOTOR 2 has no such thing" is not confusable with
    // "not looked at yet".
    return R(referenceVa);
}

uintptr_t TodoGlobal(uintptr_t kotor1Va) {
    return acc::game::IsKotor2() ? 0 : kotor1Va;
}

// "R() is not the identity function" — true for the relink (which remaps) and
// for KOTOR 2 (which resolves everything to 0). Both mean a raw reference
// address is not safe to use without checking. The reference build and an
// unrecognised build both pass values through, so both are false.
bool IsRebased() {
    switch (acc::game::CurrentBuild()) {
        case acc::game::Build::Kotor1Relink2004:
        case acc::game::Build::Kotor2Aspyr2015:
            return true;
        default:
            return false;
    }
}

const char* ActiveBuildName() { return acc::game::BuildName(); }

}  // namespace acc::addr
